### PR TITLE
Added float16 version of quantile calculation

### PR DESCRIPTION
**Pull request by curt-tigges**
Data passed into the create() function of the FeatureStatistics object will now use a float16 function to calculate quantiles, IF the activation data was originally in float16. Other precisions will behave as they did previously.

I've added new tests to verify that this float16 version is reasonably close to the old version, which was converting float16 to float32, and also tests that cover other aspects of the create() function.

### CODE REVIEW

**Comment by jbloomAus** [comment]
Great! Will review in more detail soon. Can you check if we're able to up the number of prompts without getting further ooms now?

**Comment by curt-tigges** [comment]
Is there a specific scenario (model, number of prompts) I can check?

**Comment by hijohnnylin** [comment]
If the test is “the number of prompts should just make the job take longer,
but not cause OOM”, can try this:

gemma-2-2b
any of the 65k
192000 prompts
128 context tokens
batch size 256 (or 512)

**Comment by curt-tigges** [comment]
Still getting OOMs with those settings, unfortunately. I will look into this as a separate issue.

**Comment by hijohnnylin** [comment]
does it OOM with batch size 128? or 64?

**Comment by jbloomAus** [comment]
Mostly good. I think we should always go to lower dtype if possible. We'll never use torch.float16, rather torch.bfloat16 so that check likely needs fixing.

**Pull request merged**
